# Generated by Django 3.0.6 on 2020-06-25 15:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_article_comm_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='add_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
