# Generated by Django 3.0.6 on 2020-06-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_article_add_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='add_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
