# Generated by Django 3.0.6 on 2020-05-24 09:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('full_name', models.CharField(default='', max_length=100)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None)),
                ('user_roles', models.CharField(choices=[('researcher', 'Researcher'), ('lecturer', 'Lecturer'), ('professor', 'Professor'), ('student_doctoral', 'Student - Doctoral Student'), ('student_master', 'Student - Master'), ('student_bachelor', 'Student - Bachelor'), ('librarian', 'Librarian'), ('other', 'Other')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
