# Generated by Django 3.0.6 on 2020-06-13 19:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0005_user_user_preference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_preference',
        ),
        migrations.AddField(
            model_name='user',
            name='authors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None),
        ),
    ]
