# Generated by Django 3.0.6 on 2020-06-13 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0006_auto_20200613_1926'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['email']},
        ),
    ]
